AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
